package application;

import javafx.fxml.FXML;

import javafx.scene.control.ToggleGroup;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ToggleButton;

import javafx.scene.control.PasswordField;

import javafx.scene.shape.Circle;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class GestionPatientsController {
	@FXML
	private Label time;
	@FXML
	private Label name;
	@FXML
	private ToggleButton Accueil_button;
	@FXML
	private ToggleGroup Gr;
	@FXML
	private ToggleButton users_button;
	@FXML
	private ToggleButton patients_button;
	@FXML
	private ToggleButton radios_button;
	@FXML
	private ToggleButton actes_button;
	@FXML
	private Circle circle;
	@FXML
	private ToggleButton info;
	@FXML
	private ToggleGroup Gr1;
	@FXML
	private ToggleButton dentistes;
	@FXML
	private ToggleButton assistants;
	@FXML
	private TableView assistantsData;
	@FXML
	private TableColumn assistantID;
	@FXML
	private TableColumn assistantNom;
	@FXML
	private TableColumn assistantCIN;
	@FXML
	private TableColumn assistantTel;
	@FXML
	private TableColumn assistantDate;
	@FXML
	private TextField newName;
	@FXML
	private TextField newCIN;
	@FXML
	private TextField newTel;
	@FXML
	private TextField newLogin;
	@FXML
	private PasswordField newPass;
	@FXML
	private PasswordField newPass2;
	@FXML
	private PasswordField adminPass;
	@FXML
	private Label addMsg;

	// Event Listener on Button.onAction
	@FXML
	public void SeDeconnecter(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ToggleButton[#Accueil_button].onAction
	@FXML
	public void Accueil(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ToggleButton[#users_button].onAction
	@FXML
	public void users(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ToggleButton[#patients_button].onAction
	@FXML
	public void patients(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ToggleButton[#radios_button].onAction
	@FXML
	public void radios(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ToggleButton[#actes_button].onAction
	@FXML
	public void actes(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ToggleButton[#info].onAction
	@FXML
	public void infoPerso(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ToggleButton[#dentistes].onAction
	@FXML
	public void dentistes_butt(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ToggleButton[#assistants].onAction
	@FXML
	public void assistantsButt(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void edit(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void delete(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void add(ActionEvent event) {
		// TODO Autogenerated
	}
}
